# Generated by Django 2.2 on 2019-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.CharField(default=-1, max_length=40, verbose_name='Documento de identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default=-1, max_length=40, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='ciudad',
            field=models.CharField(max_length=40, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=40, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institucion',
            field=models.CharField(max_length=40, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=40, verbose_name='Teléfono'),
        ),
    ]
